apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-spring-boot-cloud-event-consumer
  
spec:
  template:
    metadata:
      name: hello-spring-boot-cloud-event-consumer
      annotations:
        # the minimum number of pods to scale down to
        autoscaling.knative.dev/minScale: "1"
        # the maximum number of pods to scale up to
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
        - image: javacloudintegrator/hello-spring-boot-cloud-event-consumer
